### ISSUE TITLE
Expected location in jaxb folder

### ISSUE THREAD

**Issue by Japoivvb** [DavidSiles/UF6_shop#10]
https://github.com/DavidSiles/UF6_shop/blob/fb4264d147104e79882d0429afe20dbe1a7dacd2/xml/inventory_2024-11-26.xml#L1

**Comment by DavidSiles** [comment]
![Captura de pantalla 2024-12-12 a las 19 46 44](https://github.com/user-attachments/assets/2607ef8f-06a8-4740-951f-8f10d06eefa6)
![Captura de pantalla 2024-12-12 a las 19 46 55](https://github.com/user-attachments/assets/8164aa3d-a368-4ae6-bf66-4e2e6ab9251e)
![Captura de pantalla 2024-12-12 a las 19 47 03](https://github.com/user-attachments/assets/2ea81340-8032-4a07-b1e2-51134623ebe0)
