### ISSUE TITLE
Wrong element name

### ISSUE THREAD

**Issue by Japoivvb** [DavidSiles/UF6_shop#11]
https://github.com/DavidSiles/UF6_shop/blob/fb4264d147104e79882d0429afe20dbe1a7dacd2/xml/inventory_2024-11-26.xml#L11

**Comment by DavidSiles** [comment]
![Captura de pantalla 2024-12-12 a las 19 42 40](https://github.com/user-attachments/assets/385f27a9-3257-4fcf-abd5-43c1c14bcd42)
![Captura de pantalla 2024-12-12 a las 19 43 29](https://github.com/user-attachments/assets/a2240d76-574c-411d-a141-646c4d5a8e95)
