### ISSUE TITLE
character ; is missed at the end of total line

### ISSUE THREAD

**Issue by Japoivvb** [DavidSiles/UF6_shop#3]
https://github.com/DavidSiles/UF6_shop/blob/3a8670137ff4035ae86aea923acaee66d00c9278/src/dao/DaoImplFile.java#L95

**Comment by DavidSiles** [comment]
https://github.com/DavidSiles/UF6_shop/blob/16b0f56eb8a291ba3a576ce71fd8d0defb014b57/src/dao/DaoImplFile.java#L109
