### ISSUE TITLE
check currency attribute naming with the defined in document

### ISSUE THREAD

**Issue by Japoivvb** [DavidSiles/UF6_shop#7]
https://github.com/DavidSiles/UF6_shop/blob/c6212d54d31d20498c2d33e34eadc2517a2f44ed/files/inventory_2024-11-03.xml#L5

**Comment by DavidSiles** [comment]
![Captura de pantalla 2024-11-26 103953](https://github.com/user-attachments/assets/2e21ee8d-3ebf-40cf-8f9f-126f2c2ab31a)
