### ISSUE TITLE
it should use static attribute product.totalProducts

### ISSUE THREAD

**Issue by Japoivvb** [DavidSiles/UF6_shop#8]
https://github.com/DavidSiles/UF6_shop/blob/c6212d54d31d20498c2d33e34eadc2517a2f44ed/src/dao/xml/DomWriter.java#L51

**Comment by DavidSiles** [comment]
![Captura de pantalla 2024-11-26 105019](https://github.com/user-attachments/assets/c80e1611-c653-42be-99ba-6841d4371edc)
![Captura de pantalla 2024-11-26 105032](https://github.com/user-attachments/assets/8e8e9f86-ba93-4ac9-8cb8-578efa2021e5)
